baseURL = "https://music.pgersl.xyz/"
languageCode = "en-us"
title = "Petr Geršl - Music"
uglyURLs = "false"
enableEmoji = "true"
[markup]
  [markup.goldmark.renderer]
    unsafe = "true"
[params]
    description = "The official website of Petr Geršl dedicated to his music"
[outputs]
    home = ['HTML', 'JSON', 'RSS']
    page = ['HTML']
[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
[menus]
    [[menus.main]]
        name = "About"
        url = "/about"
        weight = "1"
        identifier = "Read about this site and everything you can find on it. Find out, how the site works and look on its updates throughout time. Read about me, Petr Geršl."
    [[menus.main]]
        name = "Posts"
        url = "/posts"
        weight = "2"
        identifier = "Read about the music I create, what I am up to and latest updates on my work."
    [[menus.main]]
        name = "Compositions"
        url = "/compositions"
        weight = "3"
        identifier = "Listen to my pieces and find out more about each one of them."
    [[menus.main]]
        name = "Discography"
        url = "/discography"
        weight = "4"
        identifier = "Browse my collections of compositions by albums."
    [[menus.main]]
        name = "Support"
        url = "/support"
        weight = "5"
        identifier = "Consider supporting me and what I am doing via sharing my work, or, if you really enjoy what I create, through personal donations and using Bandcamp."