baseURL = "https://music.pgersl.xyz/"
languageCode = "en-us"
title = "Petr Geršl - Music"
uglyURLs = "false"
enableEmoji = "true"
[params]
    description = "The official website of Petr Geršl dedicated to his music"
[outputs]
    home = ['HTML', 'JSON', 'RSS']
    page = ['HTML']
[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
[menus]
    [[menus.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = "1"
    [[menus.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = "2"
    [[menus.main]]
        identifier = "compositions"
        name = "Compositions"
        url = "/compositions"
        weight = "3"
    [[menus.main]]
        identifier = "biography"
        name = "Biography"
        url = "/biography"
        weight = "4"